CRITICAL - 2024-03-28 06:52:09 --> Error: Class 'App\Model\ModelPegawai' not found
in APPPATH\Controllers\Pegawai.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Pegawai->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-28 06:56:51 --> Error: Class 'App\Models\ModelPegawai' not found
in APPPATH\Controllers\Pegawai.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Pegawai->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-28 07:03:00 --> Error: Class 'App\Models\ModelPegawai' not found
in APPPATH\Controllers\Pegawai.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Pegawai->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-28 07:08:35 --> Error: Class 'App\Models\ModelPegawai' not found
in APPPATH\Controllers\Pegawai.php on line 18.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Pegawai->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-28 07:20:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'ci4-restapi', 3306, '', 0)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#11 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#3 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-28 07:20:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pegawai` (`nama`, `email`) VALUES (:nama:, :email:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Pegawai->create()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-28 07:22:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'ci4-restapi', 3306, '', 0)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#11 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#3 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-28 07:22:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pegawai` (`nama`, `email`) VALUES (:nama:, :email:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Pegawai->create()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-28 07:24:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'ci4-restapi', 3306, '', 0)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#11 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#3 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-28 07:24:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pegawai` (`nama`, `email`) VALUES (:nama:, :email:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Pegawai->create()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-28 07:25:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'ci4-restapi', 3306, '', 0)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#4 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#11 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\ci4restapi\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4restapi\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4restapi\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pe...', Array, false)
#3 C:\xampp\htdocs\ci4restapi\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\ci4restapi\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\ci4restapi\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\ci4restapi\app\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(941): App\Controllers\Pegawai->create()
#9 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#10 C:\xampp\htdocs\ci4restapi\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4restapi\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-03-28 07:25:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pegawai` (`nama`, `email`) VALUES (:nama:, :email:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Pegawai.php(44): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Pegawai->create()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
